/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    CallToActionButton: typeof import('./src/components/CallToActionButton.vue')['default']
    ChecklistItemCard: typeof import('./src/components/ChecklistItemCard.vue')['default']
    GrowingVegetableCard: typeof import('./src/components/GrowingVegetableCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InfoCard: typeof import('./src/components/InfoCard.vue')['default']
    MaterialsCard: typeof import('./src/components/MaterialsCard.vue')['default']
    PlantNewVegetableCard: typeof import('./src/components/PlantNewVegetableCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToDoCard: typeof import('./src/components/ToDoCard.vue')['default']
    VegetableCard: typeof import('./src/components/VegetableCard.vue')['default']
    VegetableChecklistCard: typeof import('./src/components/VegetableChecklistCard.vue')['default']
    VideoCard: typeof import('./src/components/VideoCard.vue')['default']
    WhereToBuyCard: typeof import('./src/components/WhereToBuyCard.vue')['default']
  }
}
